name: Coverage
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install
      run: npm ci
    - name: Test
      run: npm test -- --coverage
    - name: Coveralls
      uses: coverallsapp/github-action@v2.0.0
